class Chars{
  static const List<String> charlist =[
    "Aang",
    "Zuko",
    "Katara",
    "Sokka",
    "Toph",
    "Azula",
    "Iroh",
    "Yue",
    "Ozai",
    "Suki",
    "Bumi",
    "Roku",
    "Mai",
  ];
  static const List<String> aciklama =[
    "Avatar",
    "Ateş Bükücü",
    "Su Bükücü",
    "Bükme yeteneği yok",
    "Toprak Bükücü",
    "Yıldırım/Ateş Bükücü",
    "Ateş Bükücü",
    "Bükme yeteneği yok",
    "Ateş Kralı",
    "Bükme yeteneği yok",
    "Toprak Bükücü",
    "Avatar",
    "Bükme yeteneği yok",
  ];
  static const List<String> kucukresim =[
    "hava gezginleri.png",
    "ateş ulusu.png",
    "su_kabilesi.png",
    "su_kabilesi.png",
    "toprak krallığı.png",
    "ateş ulusu.png",
    "ateş ulusu.png",
    "su_kabilesi.png",
    "ateş ulusu.png",
    "toprak krallığı.png",
    "toprak krallığı.png",
    "ateş ulusu.png",
    "ateş ulusu.png",
  ];
  static const List<String> resim =[
    "aang1.jpg",
    "zuko1.png",
    "katara1.png",
    "sokka.png",
    "toph1.jpg",
    "azula1.jpg",
    "iroh1.jpg",
    "yue1.jpg",
    "ozai1.jpg",
    "suki1.png",
    "bumi1.png",
    "roku1.jpg",
    "mai1.jpg",
  ];
}